name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 124.43.162.220
          username: super
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # paste your private key into this secret
          fingerprint: "SHA256:mm6/M98xzH6LeDbeOhKy7zqBSK1MlmRXh6R9IMuK2yc" # server ECDSA fingerprint
          script_stop: true
          command_timeout: 30m
          script: |
            set -euo pipefail
            /opt/reportsystem/ReportSystem4/deploy.sh
